- add stage 2
mvinogradovHub/java-explore-with-me pull request #3
Opened 2023-08-02 07:19 UTC by mvinogradovHub

2023-08-02 10:44 UTC, TomattmanYandex requested changes
Комменты в коде

2023-08-02 10:44 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/controller/publicly/EventPublicController.java
> +        return eventService.getEvents(text, categories, paid, rangeStart, rangeEnd, onlyAvailable, sort, from, size, request);
многда чтобы избежать большого количество параметров в методах, вместо множества параметров, создают жто, которая содержит все эти поля, и передают только один параметр

2023-08-02 10:44 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/dto/CompilationDto.java
> +    Long id;
модификаторы доступа

2023-08-02 10:44 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/model/ApiError.java
> +    List<Exception> errors;
модификаторы досутпа

2023-08-02 10:44 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/model/ApiError.java
> +package ru.practicum.ewm.model;
это скорее дто чем моель, а можно вообще закинуть в пакет к ошибкам

2023-08-02 10:44 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    public EventFullDto addUserEvent(Long userId, EventNewDto eventNewDto) {
я бы переименовал
действие с чем действие, кем действие
addEventByUser

2023-08-02 10:44 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    public EventFullDto getUserEvent(Long userId, Long eventId) {
аналогично

2023-08-02 10:44 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    private <T> void updateEvent(Event event, EventUpdateDto<T> updateDto) {
зачем тут дженерики?

2023-08-02 11:40 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/controller/publicly/EventPublicController.java
> +        return eventService.getEvents(text, categories, paid, rangeStart, rangeEnd, onlyAvailable, sort, from, size, request);
Получается мне нужно будет руками создавать гетеры этого объекта, который в случае null будет возвращать нужно значение? Но кажется такой подход не сильно проще и наглядней чем множество параметров. Есть другой способ?

2023-08-02 11:40 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    private <T> void updateEvent(Event event, EventUpdateDto<T> updateDto) {
Я не знаю делает так кто или так не принято, но решил попробовать ). Суть вот в чем: В EventService есть два действия обновления события - updateUserEvent и updateAdminEvent. Большую часть действий по обновлению полей они делают одинаково, поэтому я решил эту часть вынести в отдельный метод updateEvent. Только вот не задача, у updateUserEvent и updateAdminEvent на вход приходят разные dto, а отличаются они только статусами. Для админа у меня статусы в EventStateAdminAction, а для пользователя EventStateUserAction. Ну так вот я подумал что вместо статуса в EventUpdateDto лучше указать дженерик, чтобы метод обновления мог работать с одним объектом, в котором тип статуса передается дженериком.

2023-08-02 11:44 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/dto/CompilationDto.java
> +    Long id;
fix

2023-08-02 11:44 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/model/ApiError.java
> +    List<Exception> errors;
fix

2023-08-02 11:44 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/model/ApiError.java
> +package ru.practicum.ewm.model;
fix

2023-08-02 11:58 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    public EventFullDto addUserEvent(Long userId, EventNewDto eventNewDto) {
fix

2023-08-02 11:58 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    public EventFullDto getUserEvent(Long userId, Long eventId) {
fix

2023-08-02 13:28 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    private <T> void updateEvent(Event event, EventUpdateDto<T> updateDto) {
убрал дженерик

2023-08-03 06:45 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/controller/publicly/EventPublicController.java
> +        return eventService.getEvents(text, categories, paid, rangeStart, rangeEnd, onlyAvailable, sort, from, size, request);
геттеры и сетеры создает lombok 
а вообще это необходимо для того чтобы не запутаться в передаваемых параметрах

2023-08-03 06:48 UTC, TomattmanYandex approved these changes
Принято

2023-08-03 07:03 UTC, merged