Feature moderation enhancement
mvinogradovHub/java-explore-with-me pull request #4
Opened 2023-08-07 14:37 UTC by mvinogradovHub

2023-08-08 10:35 UTC, TomattmanYandex requested changes
Привет, вроде по коду все хорошо, вот только есть вопросы по функционалу
1) ветка называется модерация админом, а функционал комментов
2) комменты могут только удаляться и редактироваться но не добавляться

лично мое мнение, что можерация, это добавить статус ивенту, который по умолчанию имеет одно состояние, и только админ может привести его в какое то другое состояние
например в обработке, подтверждено, отклонено
при создании сразу статус делается в обработке, тогда его может видеть только админ  и создатель после чего админ может посмотреть ивент и перевести его в другой статус, а дальше в зависимости от статуса разное поведение
ивент со статуст подтверждено видят все, со статусом отклонено только админ и создатель
а после редактирования ивента вне зависимости от его статуса, он снова переносится в статус в обработке

Если не нравится эта идея, то стоит объяснить свою, ибо сейчас функционал вообще не понятен

2023-08-08 10:35 UTC, TomattmanYandex commented on README.md
> +https://github.com/mvinogradovHub/java-explore-with-me/pull/4
стоит добавить информацию о проекте какую ни будь 
именно для этого нужен ридми файл

2023-08-08 12:15 UTC, mvinogradovHub commented on README.md
> +https://github.com/mvinogradovHub/java-explore-with-me/pull/4
Привет.  Я разделил задания на требования. В итоге вот что получилось
1.	администратор может выгружать все события, ожидающие модерации
2.	администратор может менять статус события если не прошло модерацию
3.	администратор может оставлять комментарий для инициатора события, если оно не прошло модерацию
4.	инициатор может исправить замечания, если оно не прошло модерацию
5.	инициатор может отправить событие на повторную модерацию.

В итоге получается следующее
1. Ожидающие модерацию события имеют статус PENDING. В этот статус событие переходит сразу после создания пользователем. Т.к. у администратора есть метод поиска событий с возможностью фильтрации по states, то делать ничего не потребовалось. Требование уже реализовано.
2. События со статусом PENDING только администратор может опубликовать (статус PUBLISHED), либо может отклонить (статус CANCELED). Т.е. требование уже реализовано и делать тут ничего не требуется
3. Тут получается, что при изменении статуса администратором на статус CANCELED, он должен иметь возможность добавить комментарий. Для этого во входной DTO EventUpdateByAdminDto метода PATCH admin/events/{eventId} (Редактирование данных события и его статуса (отклонение/публикация))  я добавил поле комментария commentOnRejection. Так как в требованиях четко сказано что коммент можно добавить только при отклонении, то специально не делал отдельного контроллера для этого, а добавление идет вместе с отменой. Плюс добавлены проверки чтобы нельзя было добавить коммент при публикации. Также мне показалось что у админа всеже должна быть возможность отредактировать и удалить оставленный коммент (хоть этого и нет в требованиях), поэтому я добавил эту функциональность отдельными эндпойнтами.  
4 и 5. Эта функциональность и так есть у пользователя с помощью метода PATCH /users/{userId}/events/{eventId}, изменив нужные поля и указав во входящем объекте stateAction = SEND_TO_REVIEW. Делать ничего не потребовалось.

P.S. Вообще я начал с того что начал продумывать новую статусную модель. Однако, изменение статусной модели приведет к тому, что некоторые постман тесты второго этапа перестанут работать, поэтому этот вариант я быстро отбросил.

2023-08-09 09:26 UTC, mvinogradovHub commented on README.md
> +https://github.com/mvinogradovHub/java-explore-with-me/pull/4
Добавил описание реализации в readme

2023-08-10 08:57 UTC, TomattmanYandex requested changes
Все еще вижу где то промах в логике
смысл от модерации, если она никак не задействуется, просто чтобы порадовать админов и дать им немного воображаемой власти?

2023-08-10 08:57 UTC, TomattmanYandex commented on README.md
> +https://github.com/mvinogradovHub/java-explore-with-me/pull/4
1) не вижу эндпоинта на создание коментария,
2) вот это все стоит написать в ридми файле, чтобы тот кто будет смотерть код, понял что там вообще происходит

2023-08-10 08:57 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/controller/admin/EventAdminController.java
> +    public EventFullPrivateDto updateEvent(@PathVariable Long eventId, @RequestBody @Valid EventUpdateByAdminDto event) {
я уже писал, непонятно как создаются комменты, а так как комменты это отдельная сущность, следует разделить их создание от обновления ивентов
лучше создать новую дто для обновления статуса которая будет содержать статус, и коммент который будет опциональный, а не обновлять все отправляя целый обьект ивента

2023-08-10 08:57 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    public EventFullPrivateDto getEventByUser(Long userId, Long eventId) {
по имени метода я не могу понять, это возвращаются ивенты пользователя для него самого или просто все его ивенты для всех пользователей, но в любом случае нигде нету фильтрации по статусу ивента, , т.е. админ может реджектнуть, или на апрувнуть ивент, но он все равно будет показываться

2023-08-10 15:36 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    public EventFullPrivateDto getEventByUser(Long userId, Long eventId) {
поменял название. Пользовательский теперь getUserHisEvent, а публичный остался getEvent. В публичном ограничение выдачи только опубликованных событий задается запросным методом findByIdAndState. В публичном методе поиска событий getEvents добавил BooleanExpression на статус PUBLISHED

2023-08-10 15:37 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/controller/admin/EventAdminController.java
> +    public EventFullPrivateDto updateEvent(@PathVariable Long eventId, @RequestBody @Valid EventUpdateByAdminDto event) {
Сделал администратору  отдельный DTO EventModerationByAdminDto и отдельный эндпоинт для управления статусами и отправки комментов PATCH /admin/events/{}/moderation

2023-08-11 05:57 UTC, TomattmanYandex requested changes
Все еще нету никакого ограничения по статусам, т.е. мы как могли получить все ивенты со статусами REJECTED ит.д. так все еще можем
Пожалуйста, соберись, запиши все что нужно сделать, и проверь чтобы все это можно было сделать
1) чтобы админ мог получать и изменять статусы ивентов
2) чтобы создателю были видны все ивенты вне зависимости от статуса
3) чтобы другим пользователям были видны и они могли работать только с апрувнутыми ивентами

просмотри пожалуйста еще раз логику сервисов, сейчас тамм методы такой длинны и структуры, что тяжело понять что внутри происходит, попробуй разбить на приватные методы, каждый из которыйх будет отвечать за конкретную функциональность, например, проверка валидации, проверка статусов и т.д.
Проверь после обновления ивента пользователем, нам скорее всего надо будет его полностью пересматривать, ибо мало ли что там пользователь изменил

2023-08-11 05:57 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/model/EventState.java
> +    MODERATION,
pending и moderation могут быть одним статусом, чаще всего, если есть модерация админом, то есть два варианта обработки, или без модерации ничего не показывается, и тогда pending и moderation это одно и то же, либо модерируется в случайное время, и тогда нужны только статусы PUBLISHED,    CANCELED

2023-08-11 05:57 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    public EventFullPrivateDto getUserHisEvent(Long userId, Long eventId) {
зачем нужны переименования этих методов? при чем тут HIt?

2023-08-11 05:57 UTC, TomattmanYandex commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
всякие валидации можно вынести в отдельный метод, чтобы в текущем не было такого полотна кода, обрабтку изменения статусов, тоже можно вынести в отдельный метод, ну или как минимум проверку (сделать метод который принемает 3 параметра начальный статус, конечный статус, и флаг админа, который будет возвращать true или false можно или нет переводить из одного статуса в другой)

2023-08-11 09:59 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
на методы разделил

2023-08-11 10:00 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +    public EventFullPrivateDto getUserHisEvent(Long userId, Long eventId) {
в предыдущем ревью вы писали "по имени метода я не могу понять, это возвращаются ивенты пользователя для него самого или просто все его ивенты для всех пользователей". Поэтому я переименовал. Дословный перевод метода "получить у пользователя его событие".

2023-08-11 10:02 UTC, mvinogradovHub commented on ewm-service/src/main/java/ru/practicum/ewm/model/EventState.java
> +    MODERATION,
Изначально у меня так и было, но в одном из первых ревью вы мне написали: "только админ может привести его в какое то другое состояние например в обработке, подтверждено, отклонено". Тут я подумал действительно, будет полезно иметь статус в обработке, чтобы пока админ проверяет, пользователь не имел доступ к редактированию события. Т.е. пользователь создал событие, оно в статусе "ожидает проверки". Тут пока админ не взял задачу в работу, пользователь еще может что-то подправить. Потом админ берет в работу и проверяет, а дальше либо публикация, либо отмена.

2023-08-11 10:03 UTC, mvinogradovHub commented
По логике приложения отмененные события не могут просматривать только публичные эндпойнты. Автор и админ могут видеть события всегда. Так публичных эдпойнта всего два:  GET /events? и GET /events/{eventId}. В первом ограничение указано сразу при сборке предикатов как BooleanExpression resultExpression = QEvent.event.state.eq(EventState.PUBLISHED). Во втором при получении события из репозитория Event event = eventRepository.findByIdAndState(eventId, EventState.PUBLISHED). 
Я не могу понять откуда берется ваше утверждение что мы все также можем получить REJECTED?

Также реализовано, что пользователь не может обновлять опубликованное событие и то, которое на модерации. Те, что в ожидании модерации и отменены конечно можно обновлять, но они перед публикацией все равно попадут на модерацию.

2023-08-11 14:04 UTC, TomattmanYandex approved these changes
Принято

2023-08-21 05:52 UTC, merged